name 'zabbix'
maintainer 'Thomas Vincent'
maintainer_email 'thomasvincent@example.com'
license 'Apache-2.0'
description 'Installs and configures Zabbix'
version '1.0.0'
chef_version '>= 18.0'
source_url 'https://github.com/thomasvincent/chef-zabbix-cookbook'
issues_url 'https://github.com/thomasvincent/chef-zabbix-cookbook/issues'

supports 'ubuntu', '>= 20.04'
supports 'debian', '>= 11.0'
supports 'centos', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'amazon', '>= 2.0'
supports 'rocky', '>= 8.0'
supports 'alma', '>= 8.0'

depends 'build-essential', '>= 8.0'
depends 'yum-epel', '>= 4.0'
depends 'apt', '>= 8.0'
depends 'postgresql', '>= 12.0'
depends 'mysql', '>= 11.0'
depends 'nginx', '>= 14.0'
depends 'apache2', '>= 9.0'
depends 'selinux', '>= 5.0'

provides 'zabbix::default'
provides 'zabbix::agent'
provides 'zabbix::server'
provides 'zabbix::web'
provides 'zabbix::database'