name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Install Chef
      run: gem install chef-cli
    - name: Install dependencies
      run: bundle install
    - name: Check Ruby syntax
      run: bundle exec chef exec ruby -c -w $(find . -name "*.rb" -not -path "./vendor/*")
    - name: Check Chef syntax with Cookstyle
      run: bundle exec cookstyle
    - name: Run ChefSpec tests with coverage
      run: bundle exec rspec --format documentation --format RspecJunitFormatter --out rspec.xml
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: rspec-results
        path: rspec.xml
    - name: Upload coverage results
      uses: actions/upload-artifact@v3
      with:
        name: coverage-results
        path: coverage/

  integration:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, centos-stream-8, centos-stream-9, rockylinux-8, debian-11, amazon-2]
        suite: [default, ssl, multi-vhost, modules, performance-tuning]
      fail-fast: false
    env:
      CHEF_LICENSE: accept-silent
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
      DOCKER_MEMORY: "2048m"
      DOCKER_CPUS: "2"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Install Chef
      run: gem install chef-cli
    - name: Install dependencies
      run: bundle install
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Free disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
    - name: Test Kitchen
      run: |
        bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }} --destroy=always
    - name: Upload kitchen logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: kitchen-logs-${{ matrix.suite }}-${{ matrix.os }}
        path: .kitchen/logs/

  source-install:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-20.04, centos-stream-8]
        suite: [source]
      fail-fast: false
    env:
      CHEF_LICENSE: accept-silent
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
      DOCKER_MEMORY: "2048m"
      DOCKER_CPUS: "2"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Install Chef
      run: gem install chef-cli
    - name: Install dependencies
      run: bundle install
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Free disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
    - name: Test Kitchen for Source Installs
      run: |
        bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }} --destroy=always
    - name: Upload kitchen logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: kitchen-logs-${{ matrix.suite }}-${{ matrix.os }}
        path: .kitchen/logs/
        
  prefork-mpm:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-20.04, centos-stream-8]
        suite: [prefork-mpm]
      fail-fast: false
    env:
      CHEF_LICENSE: accept-silent
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
      DOCKER_MEMORY: "2048m"
      DOCKER_CPUS: "2"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Install Chef
      run: gem install chef-cli
    - name: Install dependencies
      run: bundle install
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Free disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
    - name: Test Kitchen for MPM Prefork
      run: |
        bundle exec kitchen test ${{ matrix.suite }}-${{ matrix.os }} --destroy=always
    - name: Upload kitchen logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: kitchen-logs-${{ matrix.suite }}-${{ matrix.os }}
        path: .kitchen/logs/