---
driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  # Docker memory limits for CI environments
  memory: <%= ENV['DOCKER_MEMORY'] || '1024m' %>
  cpus: <%= ENV['DOCKER_CPUS'] || 2 %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  chef_license: accept-silent
  enforce_idempotency: true
  multiple_converge: 2
  # Add Chef Compliance Phase
  client_rb:
    data_collector.mode: :solo
    compliance.profiles.upload: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl

  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl
        
  - name: ubuntu-24.04
    driver:
      image: dokken/ubuntu-24.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl

  - name: debian-11
    driver:
      image: dokken/debian-11
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl
        
  - name: debian-12
    driver:
      image: dokken/debian-12
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl

  - name: centos-stream-8
    driver:
      image: dokken/centos-stream-8
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl

  - name: centos-stream-9
    driver:
      image: dokken/centos-stream-9
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl

  - name: amazon-2
    driver:
      image: dokken/amazonlinux-2
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl
        
  - name: amazon-2023
    driver:
      image: dokken/amazonlinux-2023
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl

  - name: rockylinux-8
    driver:
      image: dokken/rockylinux-8
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl
        
  - name: rockylinux-9
    driver:
      image: dokken/rockylinux-9
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl

  - name: opensuse-leap-15
    driver:
      image: dokken/opensuse-leap-15
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN zypper -n install sudo curl